using CodeGen;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using UnityEditor;

namespace GOAP.EditorView
{
    // 生成 GOAP 运行时注册表，把 Editor 侧类型发现结果固化为 Runtime 静态入口。
    public static class GOAPRegistryGenerator
    {
        private const string GeneratedFile =
            "Assets/GOAP/Generated/GOAPGeneratedRegistry.g.cs";

        [MenuItem("Tools/GOAP/Generate Registry", priority = 100)]
        public static void GenerateMenu()
        {
            Generate();
        }

        public static void Generate()
        {
            var entries = CollectActionEntries();
            var writer = new CSharpCodeWriter();
            writer.WriteLine("// <auto-generated/>");
            writer.WriteLine("// 由 Tools/GOAP/Generate Registry 生成，请勿手动修改。");
            writer.WriteLine("using System;");

            using (new CSharpCodeWriter.NameSpaceScop(writer, "GOAP.Generated"))
            {
                using (new CSharpCodeWriter.Scop(writer, "public static class GOAPGeneratedRegistry"))
                {
                    writer.WriteLine("private static bool _initialized;");
                    writer.NewLine();
                    writer.WriteLine("#if UNITY_EDITOR");
                    writer.WriteLine("[UnityEditor.InitializeOnLoadMethod]");
                    writer.WriteLine("#endif");
                    writer.WriteLine("[UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.BeforeSceneLoad)]");
                    using (new CSharpCodeWriter.Scop(writer, "public static void Init()"))
                    {
                        writer.WriteLine("if (_initialized)");
                        using (new CSharpCodeWriter.TableScope(writer))
                            writer.WriteLine("return;");
                        writer.WriteLine("_initialized = true;");
                        writer.WriteLine("RegisterActions();");
                    }

                    using (new CSharpCodeWriter.Scop(writer, "private static void RegisterActions()"))
                    {
                        foreach (var entry in entries)
                        {
                            writer.WriteLine(
                                $"GOAP.GOAPRuntimeRegistry.RegisterAction<{entry.DataTypeName}>(typeof(GOAP.TSerializedActionData<{entry.DataTypeName}>), {entry.RunnerExpression});");
                        }
                    }
                }
            }

            if (GeneratorUtils.WriteToFile(GeneratedFile, writer.ToString()))
                AssetDatabase.Refresh();
        }

        private static List<ActionEntry> CollectActionEntries()
        {
            var entries = new List<ActionEntry>();
            foreach (var type in TypeCache.GetTypesDerivedFrom<ActionData>())
            {
                if (type.IsAbstract)
                    continue;

                var actionBase = FindGenericBase(type, typeof(TActionData<>));
                if (actionBase == null)
                    continue;

                var dataType = actionBase.GetGenericArguments()[0];
                entries.Add(new ActionEntry
                {
                    DataTypeName = ToTypeName(dataType),
                    RunnerExpression = GetRunnerExpression(dataType)
                });
            }

            return entries
                .GroupBy(it => it.DataTypeName)
                .Select(it => it.First())
                .OrderBy(it => it.DataTypeName, StringComparer.Ordinal)
                .ToList();
        }

        private static string GetRunnerExpression(Type dataType)
        {
            var runnerBase = typeof(TActionRunner<>).MakeGenericType(dataType);
            var runnerType = TypeCache.GetTypesDerivedFrom(runnerBase)
                .Where(it => !it.IsAbstract)
                .OrderBy(it => it.FullName, StringComparer.Ordinal)
                .FirstOrDefault();

            if (runnerType == null)
                return "null";

            var runnerTypeName = ToTypeName(runnerType);
            var instanceMember = FindInstanceMember(runnerType, runnerBase);
            if (!string.IsNullOrEmpty(instanceMember))
                return $"{runnerTypeName}.{instanceMember}";

            if (runnerType.GetConstructor(Type.EmptyTypes) != null)
                return $"new {runnerTypeName}()";

            return "null";
        }

        private static string FindInstanceMember(Type runnerType, Type runnerBase)
        {
            const BindingFlags flags = BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy;

            var property = runnerType.GetProperty("Instance", flags);
            if (property != null && runnerBase.IsAssignableFrom(property.PropertyType))
                return property.Name;

            var field = runnerType.GetField("Instance", flags);
            if (field != null && runnerBase.IsAssignableFrom(field.FieldType))
                return field.Name;

            return null;
        }

        private static Type FindGenericBase(Type type, Type genericDefinition)
        {
            while (type != null && type != typeof(object))
            {
                if (type.IsGenericType && type.GetGenericTypeDefinition() == genericDefinition)
                    return type;
                type = type.BaseType;
            }
            return null;
        }

        private static string ToTypeName(Type type)
        {
            return GeneratorUtils.TypeToName(type).Replace('+', '.');
        }

        private sealed class ActionEntry
        {
            public string DataTypeName;
            public string RunnerExpression;
        }
    }
}
